Tommy
TommyLiang1/Software-Product-Sprint pull request #1
Opened 2022-06-01 23:57 UTC by TommyLiang1

The portfolio page has the MVP and is ready to merge with the main when confirmed.

2022-06-13 14:53 UTC, kmontgomery requested changes

2022-06-13 14:53 UTC, kmontgomery commented on portfolio/src/main/java/com/google/sps/servlets/HelloWorldServlet.java
> +    private String first_name = "Tommy";
This string could be final since it is a global variable and it is never changed.

2022-06-13 14:53 UTC, kmontgomery commented on portfolio/src/main/java/com/google/sps/servlets/HelloWorldServlet.java
> +        response.getWriter().println("Hello " + first_name + "!");
Why leave this as a variable if the value is always the same? If you put "Hello Tommy!" here I believe the behavior would be the same.

2022-06-13 21:49 UTC, TommyLiang1 commented on portfolio/src/main/java/com/google/sps/servlets/HelloWorldServlet.java
> +        response.getWriter().println("Hello " + first_name + "!");
Yes. You are correct. The behavior is the same if I hard coded my name into the println statement.

2022-06-14 18:19 UTC, kmontgomery commented on portfolio/src/main/java/com/google/sps/servlets/HelloWorldServlet.java
> +        response.getWriter().println("Hello " + first_name + "!");
Ok then for readability it would suggest leaving it as one string!

2022-06-14 18:20 UTC, kmontgomery commented on portfolio/src/main/java/com/google/sps/servlets/HelloWorldServlet.java
> +        response.getWriter().println("Hello " + first_name + "!");
Oh I see you did. Great :) thanks

2022-06-14 18:20 UTC, kmontgomery approved these changes

2022-06-14 18:52 UTC, merged